### ISSUE TITLE
Использовать для раздела zip-архив с коллекцией картинок

### ISSUE THREAD

**Issue by d-hurricane** [OpenBSL/YellowPM#1]
Сейчас новый раздел использует большую картинку, который ломает привычную разметку панели разделов в некоторых типовых конфигурациях:
![image](https://github.com/user-attachments/assets/0e829119-d2cd-4f03-9f31-7c0e274812e6)
Хотелось бы сохранить привычный вид разделов, для чего прошу использовать для нового раздела (подсистемы) zip-архив с коллекцией картинок разного размера.

**Comment by Bayselonarrend** [comment]
Посмотрел, как оформлены подсистемы типовых - там не коллекция, а просто маленький значок. Согласен, что выбивается, просто сделаю пока серенький 16х16 как там

**Comment by Bayselonarrend** [comment]
[0.2.0](https://github.com/OpenBSL/YellowPM/releases/tag/0.2.0)
