### ISSUE TITLE
Переименовать роль в ОбщиеПрава

### ISSUE THREAD

**Issue by d-hurricane** [OpenBSL/YellowPM#2]
Если вопрос режима совместимости расширения не принципиальный, то предлагаю:
- повысить его до версии 8.3.14
- переименовать единственную роль в "YPM_ОбщиеПрава"
- назначить ее основной ролью расширения.

В этом случае при работе в конфигурациях на базе современной БСП все объекты пакетного менеджера станут доступны всем пользователям информационной базы сразу после установки расширения. Мне кажется это более удобным, нежели "колдовать" с ролями после установки. Лучше пусть "колдуют" те, кто решит ставить пакетный менеджер на прод.

**Comment by Bayselonarrend** [comment]
> Если вопрос режима совместимости расширения не принципиальный

Тут принцип максимально низкой версии - ниже версия, больше людей. Хотелось бы еще ниже, чем сейчас, но проблемы с ограничением возможностей расширений

> В этом случае при работе в конфигурациях на базе современной БСП

А что будет при работе в конфигурациях со старой или без БСП?

**Comment by d-hurricane** [comment]
> А что будет при работе в конфигурациях со старой или без БСП?

Ничего. Не знаю с какой версии, но теперь БСП в случае обнаружения в расширении основной роли с именем "ОбщиеПрава" затягивает ее во все возможные профили доступа, в т.ч. и административные. Почему и не требуется потом ничего доделывать в конфигурации расширения и назначать роль через конфигуратор.

**Comment by Bayselonarrend** [comment]
[0.2.0](https://github.com/OpenBSL/YellowPM/releases/tag/0.2.0)
