### ISSUE TITLE
Таблица файлов - расширение cf

### ISSUE THREAD

**Issue by dqwerty555** [OpenBSL/YellowPM#5]
Судя по описанию "...При открытии обработки менеджера, он подтягивает из интернета индекс пакетов - список репозиториев, которые имеют релизы с .epf, .erf или .cfe файлами", в списке анализируемых файлов нет файлов .cf. Ограничения какие-то логические? Почему задаю вопрос - пример "https://github.com/NikolayNosakin/documentation_it_department/releases/tag/1.1.2.7", в таблице "СписокФайлов" (с переключателем "Обработки") отображается только .epf. Проверил с переключателем "Расширения", не обнаружил в списке этот репозитарий. Перешел по ссылке на страницу релизов репозитария https://github.com/NikolayNosakin/documentation_it_department/releases/tag/1.1.2.7, вижу, что выложен и файл .cf, с которым и взаимодействует эта обработка .epf. Вопрос - может, добавить в список анализируемых файлов и .cf?

**Comment by Bayselonarrend** [comment]
>Ограничения какие-то логические?

Да: в списке представлены разработки, которые можно (в теории) установить или открыть в текущей конфигурации. Т.е. обработки и расширения

**Comment by dqwerty555** [comment]
Спасибо
